# Generated by Django 5.1.3 on 2024-11-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor1Force', models.FloatField()),
                ('sensor2Force', models.FloatField()),
                ('sensor3Force', models.FloatField()),
                ('sensor4Force', models.FloatField()),
                ('sensor5Force', models.FloatField()),
                ('totalForce', models.FloatField()),
                ('readableTime', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Sensor Data',
                'verbose_name_plural': 'Sensor Data',
            },
        ),
    ]
